spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
springdoc.default-produces-media-type=application/json
server.servlet.context-path=/api/v1/


spring.datasource.url=## put your url here
spring.datasource.username=# put your username here
spring.datasource.password=# put your password here
spring.jpa.hibernate.ddl-auto=update
